[package]
name = "token-tide"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.11.23"
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["rt", "rt-multi-thread", "macros"] }
serde = { version = "1.0.193", features = ["derive"] }
prettytable-rs = "0.10.0"
clap = "4.4.11"